services:
  dbms:
    image: postgres
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:5432
    restart: always
    # volumes:
    #   - ./src/main/initdb:/docker-entrypoint-initdb.d


  dockerize:
    image: jwilder/dockerize
    environment:
      TZ: ${OS_TIMEZONE}
    command: tail -f /dev/null


  schemaspy:
    image: schemaspy/schemaspy
    volumes:
      - ./schemaspy.properties:/schemaspy.properties
      - ../docs/schemaspy:/output